### ISSUE TITLE
Colorscheme issues

### ISSUE THREAD

**Issue by jocelynmallon** [rogual/neovim-dot-app#130]
I don't know enough to really diagnose/troubleshoot, but I rebuilt both Neovim and Neovim.app from HEAD via home-brew and now certain color schemes are broken on launch in Neovim.app but work fine/as normal in terminal nvim, macvim, vimr, etc.

[hybrid theme](https://github.com/w0ng/vim-hybrid) for example: http://i.imgur.com/0CBijY9.png

fixed/working fine again after manually resetting via

    :colorscheme hybrid

http://i.imgur.com/ljV5nJO.png

The only thing I see is that running :scriptnames in terminal nvim and Neovim.app shows a different order, e.g. /runtime/syntax being loaded after the users .nvimrc

terminal nvim: https://gist.github.com/jocelynmallon/54d22981e28a2a49a31d
neovim.app: https://gist.github.com/jocelynmallon/2fed87d57925832392a3

**Comment by bambu** [comment]
This is related to https://github.com/rogual/neovim-dot-app/issues/91 and neovim issue https://github.com/neovim/neovim/issues/2216. 

Because there is currently no command line flag to force nvim to define gui_running when it is started, anything that relies on gui_running (for example both the hybrid and solarized themes) will not work properly. 

A simple fix is to reload the vimrc after attaching to the ui

**Comment by bambu** [comment]
@jocelynmallon  checkout PR #132 and let me know if the issue still occurs.

**Comment by jocelynmallon** [comment]
:+1:  Working for me, thanks for the quick fix.
