### ISSUE TITLE
signal after autocomplete 

### ISSUE THREAD

**Issue by tanrax** [rogual/neovim-dot-app#137]
![screen shot 2015-09-23 at 11 01 30](https://cloud.githubusercontent.com/assets/4553672/10041213/c9352b64-61e2-11e5-8f1c-aaaa3380a593.jpg)
![screen shot 2015-09-23 at 11 01 54](https://cloud.githubusercontent.com/assets/4553672/10041214/c9381dce-61e2-11e5-8d99-d7f6e29f70c6.jpg)

**Comment by bambu** [comment]
No entiendo lo que estas demostrando con esto. Lo puedes explicar?

**Comment by tanrax** [comment]
Que cuando desaparece el desplegable, se queda un residuo detrás. Una línea vertical a la derecha :)

**Comment by bambu** [comment]
@philplckthun can you take a look at this since you know more about the redraw calculations. 

I am able to reproduce this issue when doing autocomplete and the complete has a scrollbar (like in the 2nd picture). Upon selecting an item / pressing escape / typing more characters and reducing the list the bar appears. In my case it only appears where there is already something drawn. 

I could not reproduce this in a situation where there is no scrollbar on the auto complete popup.

**Comment by philplckthun** [comment]
@bambu I'll try to reproduce it.

**Comment by bambu** [comment]
@tanrax can you try #160 and see if fixes the redraw issue? It fixes it for me.
