### ISSUE TITLE
CMake support?

### ISSUE THREAD

**Issue by udp** [rogual/neovim-dot-app#195]
Is there a particular reason this project uses SCons when NeoVim uses CMake?  I don't have a particular preference other than being more familiar with CMake, but having different build systems for strongly related projects is annoying.

Would there be any interest if I opened a PR for CMake support?

**Comment by rogual** [comment]
It's simply because I know SCons and I don't know CMake.

If this was a project with a lot of contributors and as a whole the team preferred CMake I'd be open to switching, but for now I'd rather stick with SCons.

Is there anything in particular that the difference in build systems makes difficult, or is it just the annoyance of being able to more easily work on one than the other?
