### ISSUE TITLE
Neovim does not appears in Spotlight search

### ISSUE THREAD

**Issue by geraldus** [rogual/neovim-dot-app#205]
Hi!

I've built `neovim-dot-app` using `brew`, after `brew link` I see **Neovim** icon in Launchpad, but it is not indexed by Spotlight, hence it is not possible to launch **Neovim** from Spotlight search.  Is there some easy fix?

**Comment by rogual** [comment]
Odd! Works for me. Maybe a permissions issue? Can you post the output of `ls -l /Applications/ | grep Neovim`

**Comment by spicydonuts** [comment]
I've also always had this problem.  I checked the permissions and Neovim.app was `$USER admin`.  I changed it to match another app which works fine (using `root wheel`), but it still doesn't show up.  If I delete the symlink and use Finder to create a shortcut, it works fine.

**Comment by spicydonuts** [comment]
Here's a screenshot of Finder's "Get Info" for both icons.  Even though the alias created with Finder is still an alias, it looks completely different and is much larger.  There must be an OS X "shortcut" file that is different from a regular symlink.
<img width="551" alt="neovim" src="https://cloud.githubusercontent.com/assets/715921/13091296/b408ae08-d4b7-11e5-875c-3ff1af5f1446.png">

**Comment by steven807** [comment]
I spent quite a bit of time over the last day or two trying to understand this.  The most useful discussion seems to be here: https://github.com/Homebrew/homebrew/issues/4635
The gist seems to be that symlinks are not imported by Spotlight.  (Aliases, created by the Finder, are, so that is one of addressing the problem -- just remove the symlink, and create an alias instead.)  This is a general problem with Homebrew, and they basically say that shouldn't have supported app bundles (i.e. "brew linkapps") at all.
What I still don't understand is why I've never had this problem with MacVim.

**Comment by rogual** [comment]
Closing because 1) no reply from OP and 2) looks like a common issue for homebrew apps.

If this is happening for you, you can always just copy the app into /Applications rather than linking.
