### ISSUE TITLE
init.vim

### ISSUE THREAD

**Issue by ApolloTang** [rogual/neovim-dot-app#208]
How do I tell neovim-dot-app to load my init.vim? I have it at:  
~/.config/nvim/init.vim

**Comment by rogual** [comment]
neovim.app doesn't load init.vim, neovim itself does. Does terminal nvim load your init.vim?

**Comment by ApolloTang** [comment]
yes, ternimal nvim's :echo $MYVIMRC point to ~/.config/nvim/init.vim
but neovim-dot-app's :echo $MYVIMRC return nothing :(

**Comment by dotjairo** [comment]
I'm experiencing the same issue. I did a `brew update` and reinstalled both neovim and neovim-dot-app (`brew reinstall --HEAD neovim`, `brew reinstall --HEAD neovim-dot-app`) and still experience the same problem.

One other thing I noticed, aside from the empty `$MYVIMRC` is that the first path in `rtp` points to `/.config/nvim` instead of `~/.config/nvim` (note the missing `~`)

@ApolloTang can you confirm this? (in neovim-dot-app do `:set rtp?`)

**Comment by dotjairo** [comment]
I found my problem.  In my `.bashrc` file I had `export XDG_CONFIG_HOME=$HOME/.config`.  Replacing `$HOME` with `~` fixed it.

I'm guessing that `$HOME` evaluates to an empty string in the neovim environment spawned by neovim-dot-app. Which is confusing because if I run `:echo $HOME` it evalutaes properly to `/Users/username`.

@rogual Any idea what is going on here? I did notice that you're calling `execve()` in [`process.cc`](https://github.com/rogual/neovim-dot-app/blob/faf1c24f8cc7e1722ccf2e29b6a12160811481de/src/process.cc#L24) with an extern declared  environment (`environ`) variable. Where is it defined? I couldn't find it anywhere else in the code...

**Comment by ApolloTang** [comment]
@dotjairo 
$HOME is not evaluated 

export XDG_CONFIG_HOME=~/.config   "<-------works
export XDG_CONFIG_HOME=$HOME/.config  "<-------will not work

Thanks so much !

**Comment by rogual** [comment]
@dotjairo Not quite sure, but it wouldn't be the first bit of environment weirdness to be reported. I am also not super familiar with XDG so I couldn't tell you if what you're doing there is supported, though it looks like it should be.

`environ` is defined in I think libc? See `man environ`. It should be the current process's environment.

**Comment by ApolloTang** [comment]
it turns out that setting: 

        export XDG_CONFIG_HOME="~/.config"

will result wit conflict in other program. For example Midnight Commander will save its configuration as:

        "~/~/.config/mc/ini"

I am reverting to: 
         export XDG_CONFIG_HOME="$HOME/.config"

Please re open this issue
