### ISSUE TITLE
.config/nvim/init.vim not loading

### ISSUE THREAD

**Issue by grahams** [rogual/neovim-dot-app#217]
I have a weird problem with neovim-dot-app.  When I launch it, I get a completely "naked"  (no colors, no plugins, no settings) instance.  For instance, running :set inside of dot-app:

![neovim-dot-app :set](http://dl.dropbox.com/u/22906/Screenshots/tdfc.png)

versus what I see when I run :set from neovim running in a terminal:

![neovim :set](http://dl.dropbox.com/u/22906/Screenshots/6g4u.png)

Furthermore, when I choose the menu item Edit -> Startup Settings, the editor opens ~/.vimrc instead of ~/.config/nvim/init.vim

I updated homebrew and rebuilt neovim and neovim-dot-app.  Here is my init.vim:
https://gist.github.com/grahams/6a479cbf370eac180bfe

Any ideas?  I'm admittedly new to both neovim and dot-app so please let me know if I'm doing something wrong.

**Comment by rogual** [comment]
Not sure what's happening here. Couple of thoughts:

* Does ~/.vimrc exist?
* Does ~/.config/nvim/init.vim exist? 
* What does `:echo $MYVIMRC` give?
* Maybe you have configured your XDG config path? I don't know much about this but I believe Neovim respects an environment var named XDG_CONFIG_HOME when deciding where your init.vim should be. Try running `env` in bash and see if there's anything that looks related.

**Comment by grahams** [comment]
Both ~/.vimrc and ~/.config/nvim/init.vim exist.  

In neovim command line, $MYVIMRC is /Users/grahams/.config/nvim/init.vim
in neovim-dot-app it doesn't echo anything

host:[~(master)]$ echo $XDG_CONFIG_HOME
/Users/grahams/.config

same value from inside of nvim (:echo $XDG_CONFIG_HOME), but inside of dot-app I get:
/.config

**Comment by rogual** [comment]
that `/.config` rings a bell. Someone had a similar issue before and it turned out they had $XDG_CONFIG_HOME set to $HOME/.config, and the nested variable wasn't getting expanded.

Maybe try fiddling with the $XDG* vars, using absolute paths only? Or try removing them temporarily?

**Comment by grahams** [comment]
I replaced the $HOME/.config with /Users/grahams/.config and it now appears that dot-app is loading my rc file, which is good news.

It still doesn't seem to be correctly initializing the colors, though..  Is this syntax correct?


if exists("neovim_dot_app")
    colorscheme solarized
    set background=dark
else
    let g:solarized_termcolors=256
    set background=dark
    colorscheme solarized
endif

**Comment by rogual** [comment]
Should be. Do any colorschemes work? Some schemes try to be clever and include code to do stuff like detect GUIs. If Solarized tries to do this it may be running afoul of the fact that Neovim has removed or changed a bunch of stuff that can break GUI detection. For example, I know `has('gui_running')` can fail under Neovim.

**Comment by grahams** [comment]
Not sure, solarized is the only colorscheme I've ever used :)  I'll find a different one to try.

**Comment by grahams** [comment]
'colorscheme darkblue' works, but solarized does not...  I'll poke around inside of solarized to see what is going on.

**Comment by grahams** [comment]
I found this variant of solarized that seems to work: https://github.com/frankier/neovim-colors-solarized-truecolor-only

**Comment by DeMol-EE** [comment]
**EDIT:** Guess I'm an idiot. I changed to the solarized version that also worked for @grahams, and I deleted the following lines from the vimrc:
```
set t_Co=256
let g:solarized_termtrans = 1
let g:solarized_termcolors=256 
```
Now everything works fine. I was using [this solarized plugin](https://github.com/altercation/vim-colors-solarized). Don't understand why that won't work...

I am having the same issue, namely that neovim.app does not seem to be loading the solarized color scheme correctly. I have been transitioning from terminal+vim and have had the luxury of testing a miriad of combinations. From this, I can report that the following all works:

- iterm2 + vim
- iterm2 + nvim
- macvim

For neovim.app, however, the color scheme doesn't load correctly. Switching to a default color scheme works (pablo, torte, ...), only solarized seems to misbehave. I've included the part of my `.vimrc` that might be relevant:

```
""" COLOR SETTINGS
syntax on
set termguicolors
set t_Co=256
let g:solarized_termtrans = 1
let g:solarized_termcolors=256 
colorscheme solarized
let g:airline_theme = 'solarized'
set background=light
let g:airline_solarized_bg = 'light'
```

**The reason I am replying here is because `echo $XDG_CONFIG_HOME` from inside neovim.app does nothing, and this was one of the suggestions in this thread**. I have tried all other suggestions and found that the usual files are in the usual places. The only thing misbehaving is that neovim.app can't seem to access the XDG_CONFIG_HOME envvar. I noticed this variable was not set, so I added it to `~/.profile` (and again in `~/.zshrc` for good measure). Could it be that this is set in the wrong place, and could this be the reason why solarized won't load?
