### ISSUE TITLE
Support FZF

### ISSUE THREAD

**Issue by azag0** [rogual/neovim-dot-app#256]
It seems that `fzf#run` from FZF does not work in Neovim.app. Running
```
:call fzf#run({'source': 'ls'})
```
results in
```
Error running ls|fzf > /var/folders/[...]
```

Versions:
- neovim: 0.1.4
- Neovim.app: d6ef684 (HEAD)
- FZF plugin: junegunn/fzf@24516bc (HEAD)

**Comment by emptyflask** [comment]
Works for me using:

- nvim 0.1.5-71-geefcc50
- neovim.app HEAD (same commit as you)
- fzf 0.12.0
- fzf.vim 94bdefe

**Comment by azag0** [comment]
I've updated everything, but the issue persists.
- nvim 0.1.5-269-g6871713
- Neovim.app 2f20a422
- fzf 0.12.1

I don't use the fzf.vim plugin though. As far as I understand, it is only a collection of functions using the core `fzf#run`?

I'm on El Capitan. The problem is not related to `$PATH`.

How can I debug this further?

**Comment by emptyflask** [comment]
I'm running Yosemite, not sure if that makes a difference.

**Comment by bambu** [comment]
@azag0, I am also able to run this on El Capitan. Never used FZF, don't know what it does but copy pasting it worked. did you modify the output that you typed? when i entered your command I got a popup with the current directory and the status bar said:
```viml
term://.//66312:ls|/path/to/my/vim/plugged/fzf/bin/fzf > /var/folders/2y/rest/of/nvim/file
```
If you are just getting `fzf` then maybe the plugin is somehow failing to find the `fzf` binary. 
* Is `fzf` in your path?
* What happens when you just type `fzf` in the terminal? 
* Likewise what happens when you go to wherever the `fzf` binary is and run it?
* Are you able to do `:term` and run commands? 
* Are you able to do `:term` and go to the directory with `fzf` in it and run it?
* What happens when you only run the `fzf` plugin in Neovim.app?

These are just some of the things that I would double check when troubleshooting any plugin that use the terminal

**Comment by azag0** [comment]
Ok, I think I tracked this down, quite a corner case bug. The issue is [this](https://github.com/rogual/neovim-dot-app/blob/c00467c79236689614ede21ab6ed5e7493834e33/src/app.mm#L67) line of code. It assumes there are no `=` characters in environment variables. In my case, I have
```
FZF_DEFAULT_OPTS=--bind=ctrl-u:page-up,ctrl-d:page-down
```
So in Neovim.app, that ends up equal to `--bind`, which triggers the error. Don't know Objective-C, so cannot provide a patch.

**Comment by bambu** [comment]
@azag0 checkout #260 and see if it works for you
