### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by jojoyuji** [rogual/neovim-dot-app#57]
I have uninstalled msgpack via `brew uninstall msgpack`, `brew update` and then `brew install msgpack`
but I'm still unable to compile:

```
src/client.cc:5:10: fatal error: 'msgpack.hpp' file not found
#include <msgpack.hpp>
         ^
1 error generated.
scons: *** [build/client.o] Error 1
make: *** [all] Error 2
```

**Comment by rogual** [comment]
First, check that msgpack has installed properly:

    $ file /usr/local/include/msgpack.hpp
    /usr/local/include/msgpack.hpp: ASCII C++ program text

If you get an error, try `brew link msgpack`. Otherwise, the file is there, so check that your compiler is looking in the right place for include files:

    $ clang++ -E -x c++ - -v < /dev/null

This will give a lot of output; you're looking for

    #include <...> search starts here:
    ...(some other stuff)...
    /usr/local/include

If you don't see that, the fix is probably `xcode-select --install`

If you do, er... I don't know. Post here and we'll figure it out together.

**Comment by jojoyuji** [comment]
my compiler wasn't looking to `/usr/local/include`

I ran `xcode-select --install` and... sweet! :dancer: 

Thx again!

**Comment by rogual** [comment]
No prob. I'll add this one to the FAQ.
