### ISSUE TITLE
Cursor shape

### ISSUE THREAD

**Issue by danielepolencic** [rogual/neovim-dot-app#64]
I'm not sure if this is something to do with neovim or neovim.app
How do I change the cursor shape to be like in (Mac)Vim (first pict at the top)?

[![Cursor](http://i.imgur.com/O0NzL1y.png)](http://i.imgur.com/O0NzL1y.png)

EDIT: if I run `nvim` from the command line (iTerm2), I can see the block cursor.

**Comment by rogual** [comment]
The block cursor is only supported on OS X 10.10 at the moment — because its APIs offer an easy way to draw one. If Neovim.app gets a character buffer (which it will at some point, because other wanted features will need one) then we can draw the nicer cursor on more OS X versions.

(In case you were wondering, the reason the block cursor is harder to draw is because we need to invert what's underneath it)

**Comment by danielepolencic** [comment]
Thanks for the clarification.
