### ISSUE TITLE
Right to Left Text Rendering Improvement

### ISSUE THREAD

**Issue by khalidchawtany** [rogual/neovim-dot-app#72]
**Neovim-dot-app** improves right to left text rendering which is LOVELY. As can be seen in the screenshot below, **nvim** (in terminal) renders the rtl text from left to right, which is plain wrong :angry:.  **neovim-dot-app** renders it in the correct direction. However, there is still some issues:

* Arabic like languages have connected characters and have a different variants of charapcters based on the context. And **neovim-dot-app** sometimes does not respect this and uses wrong contextual variant. Look at the attached photo and compare the neovim-dot-app result with Mac OS *TextEdit.app*.

http://en.wikipedia.org/wiki/Arabic_alphabet#Modified_letters
http://en.wikipedia.org/wiki/Typographic_ligature

* When navigation through the text using vim motions, the cursor moves in a way as if you would be moving through the text represented by the **terminal nvim**.  For example, if I press **w** the cursor moves to the middle of a word and then if you take a loo k at **terminal nvim** you find out that cursor position is in fact the beginning of the word (in the wrong rendered form) inside **terminal nvim**.

![right_to_left](https://cloud.githubusercontent.com/assets/1681606/7162291/78371d9a-e39c-11e4-8bde-27f42087edf3.png)

**Comment by rogual** [comment]
Thanks for the bug report. So, there's two issues here.

**1. Ligatures**

I don't know but I would guess that this is something that the OSX Input Methods take care of, in which case IME support would fix this — see https://github.com/rogual/neovim-dot-app/issues/70 for more details. It is planned, but will be a fairly big job.

** 2. RTL **
I don't know whether Vim supports having bits of RTL text embedded in an LTR document. A cursory reading of `:h arabic` would suggest that text direction is per-window in Vim.

If Neovim.app is actually rendering some RTL text in the correct direction and terminal nvim isn't, then this is probably just OSX itself interpreting the Unicode text-direction markers and flipping the direction of that run of text, and I'd actually consider that a bug, because, as you can see, Vim still thinks of the text as being LTR.

I do know Vim has some Arabic-centric functionality, though I've no idea how good it is. Have you tried `:set arabic` / `:help arabic`?

If you need RTL-within-LTR and Neovim itself doesn't support it, then Neovim needs patching — it's not something we can patch in at the GUI layer (as evidenced by wrong behaviour of word-motion commands)

**Comment by khalidchawtany** [comment]
@rogual you are right that this is a bug. However, it is a useful one, at least it show the text in the direction it should be. PLEASE, let the OS X handle the drawing direction :)

As you can see in the screenshot above, it is impossible to read **terminal nvim** rendered text.

As for navigation part, I think it would be VERY hard to implement.

**Comment by rogual** [comment]
It might look right in this case, but it won't work with any stability; if Vim redraws part of that text for any reason, the display will mess up. This will happen if, for instance, you use `/` to search for some text and Vim ends up highlighting part of the RTL text. It only looks right because Vim drew that whole run of text in one go.

**Comment by khalidchawtany** [comment]
You are right. Since, sometimes the text is messed up. If I resize the window or move the cursor over it, the text is corrected (drawn in proper RTL). However, if I press ctrl-l the whole thing is messed up again just like terminal nvim.

**Comment by rogual** [comment]
I've committed https://github.com/rogual/neovim-dot-app/commit/05e1d1371741d58edb0c47a38e3799a0b583e997 to fix this bug and render text as Neovim does.

It may be possible in the future to implement (a subset of) true bidirectional text support, though, as plain Vim + `:set termbidi` + [mlterm](http://mlterm.sourceforge.net) is reported to work (though I don't know how well).

**Comment by khalidchawtany** [comment]
Please, could you provide an option to have RTL displayed correctly. Just because of this, I cannot use vim for Apps where RTL is needed, which is sad :cry: 

At least being able to read what is written is a big improvement. I usually write arabic text in another app and then get back to vim to do other stuff. However, when you cannot read what is written it makes it impossible to write anything useful.

Being able to display RTL correctly is a great improvement. I don't care about navigating RTL or editing it, as I use other apps to write the RTL in the first place.

**Comment by rogual** [comment]
Do you mean properly-properly, or just disabling https://github.com/rogual/neovim-dot-app/commit/05e1d1371741d58edb0c47a38e3799a0b583e997 ?

**Comment by khalidchawtany** [comment]
Properly-properly is super awesome. However, I don't think it's feasible.

semi-Properly-properly **display only, no navigation, no editing** (Ctrl-l should not mess it up ) is more than OK to me.

**Comment by khalidchawtany** [comment]
@rogual,  I am eagerly waiting for your response regarding RTL support :worried:

**Comment by rogual** [comment]
I can't really see any middle ground between current behaviour and proper bidi support. I don't think display-only would be any easier to implement; once display works, we might as well make editig work. It'd be weird to enable it only in readonly buffers, and probably hard to implement too.

I think the best way to go with this would be to have Neovim.app play the part of the terminal in Vim's `:set tbidi` behaviour, in which “The terminal is in charge of Bi-directionality of text (as specified by Unicode).”

This isn't a small task, and I have other priorities at the moment, so I hope you aren't waiting for me personally to implement this, but, as always, PRs are welcome.

**Comment by khalidchawtany** [comment]
Thanks @rogual. I just wanted to know your opinion regrading RTL support. I totally undrestand that there are other work with higher priorities to be done. 

I hope others are interested in RTL support or I have to learn Objective-C. Since, I don't have any knowledge about this language :(

Thanks for your hard work. I really appreciate your work :+1:
