### ISSUE TITLE
Font rendering off

### ISSUE THREAD

**Issue by kopischke** [rogual/neovim-dot-app#9]
_First things first: awesome work, I cannot wait to see where this is going!_

Neovim.app’s font rendering is not producing the same results as other OS X apps: In the screenshot below, compare MacVim (left) and Neovim (right), both using the Powerline version of Menlo at 12 pt:

Ignoring the difference in line height already mentioned in #4, you will notice that:

![macvim neovim app font rendering](https://cloud.githubusercontent.com/assets/80906/6881697/559af6e2-d56b-11e4-93f9-9488736b7c5e.png)

- while MacVim’s font rendering looks as expected on OS X, Neovim.app makes the beefy Menlo look positively wispy
- Neovim.app is unable to show _italics_ and **bold** font variants (which exist and are used by MacVim)

Note this is true independently of the font used – I also tried stock Menlo and CamingoCode, with the same overall result.

**Comment by rogual** [comment]
It looks like the different font rendering may be happening because we're drawing into an offscreen image rather than directly to the view. This CocoaDev thread suggests that the difference comes from the fact that OS X uses subpixel rendering when drawing to a view, and not when drawing to an image:

http://www.cocoabuilder.com/archive/cocoa/89603-drawatpoint-rendering-thin-light-text.html

Our drawing strategy is going to have to change anyway if https://github.com/rogual/neovim-dot-app/issues/6 doesn't get resolved, so I'm going to test out the performance of keeping a character buffer rather than an image buffer.

(You'd think re-rendering the actual text all the time would be slow, but it's easy to guess wrong about performance)

On a side note, if the lack of subpixel rendering is the issue, and we enable it somehow, it will break that recent inverted cursor patch (can't nicely invert a subpixel-rendered image). Using a character buffer would also neatly solve this issue as you can just invert the attributes and re-draw the character under the cursor.

**Comment by kopischke** [comment]
The explanation makes sense, thanks for the info. I’ll look forward to a revised rendering strategy then, as the current one severely impairs usability with mid to low contrast colour schemes with a light background.

**Comment by rogual** [comment]
I've committed a fix to this to the `cg` branch — see https://github.com/rogual/neovim-dot-app/issues/6

Just want to make sure it doesn't bring back a certain bug for certain people before I merge it.

**Comment by rogual** [comment]
OK, I've merged that branch. Would you take a look and see if it resolved this issue?

**Comment by shemerey** [comment]
I see another issue with custom patched fonts, if you use custom patched font for "PowerLine", "lightline" or any other plugin, which prettify your `statusline` you can see utf8 chars not displayed properly 

for instance  ![Status Line with patched font](https://www.evernote.com/shard/s3/sh/d7d558bd-30d3-493f-a2db-d1f0c60c4a3d/37ae7ced217e115b107ab4f9f88ce01c/res/f8d4cbf1-44c6-4fba-9e3e-ab60b5e67ad9/skitch.png) 

I am using https://github.com/itchyny/lightline.vim plugin with [Monaco for Powerline](https://gist.github.com/baopham/1838072), thx for you awesome job it's first Neovim GUI that i can really work with without to much hassle

**Comment by rogual** [comment]
Glad it's working for you! Would you mind opening the Powerline thing as a separate issue?

**Comment by kopischke** [comment]
OK, so I finally got around to re-build *Neovim.app*. Font rendering is much improved (yay sub-pixel rendering!), but still looks lighter than the equivalent in *MacVim*. However, this might be an artefact of Neovim.app both ignoring the request for bold fonts and having a different color space from other OS X apps (*Solarized light*, looking identical in MacVim and Terminal, but looking rather washed out in Neovim.app). I’ll close this and open new issues for the gamma and font variant rendering
