### ISSUE TITLE
Read equivalent of .gvimrc and set "gui_neovim"

### ISSUE THREAD

**Issue by shazow** [rogual/neovim-dot-app#91]
A couple of feature requests:

1. When you run `MacVim.app`, it'll read `$HOME/.gvimrc` just like `gvim` or `vim -g` would. It's common to set GUI-specific settings there, like a different colorscheme or font. It would be nice if NeoVim.app also read .gvimrc, or at the very least a .gnvimrc.

2. When MacVim.app runs, it injects a "gui_neovim" variable, so that you can identify the client and execute special settings for it. For example:

```
if has("gui_macvim")
    ...
endif
```

Would be nice if a similar variable was set, maybe a "gui_neovim".

(Btw, thanks for building this, works great!)

**Comment by rogual** [comment]
Hiya! Thanks for the ideas.

I'd like to develop Neovim.app as far as possible without changing the `nvim` executable itself, and I don't know a way of adding a `has(...)` variable without doing so. I do agree it would be useful to be able to detect NeoVim.app though — perhaps a good way would be to predefine a variable called, say, `neovim_dot_app` in the default `nvimrc` (https://github.com/rogual/neovim-dot-app/blob/master/res/nvimrc) which you could then detect with `exists()`?

Alternatively, I would be happy to add a `has` variable if anyone knows a pure-VimL way of doing so.

As for auto-reading `.gvimrc`, I'm undecided. We could easily add

```
if has('gui_running')
    source '~/.gvimrc'
endif
```

or similar to `nvimrc`, but this doesn't sit quite right with me because:

1. If users want to change this behaviour, it's easier to leave it out and let them add it to their own .nvimrc than it is to leave it in and leave them to somehow override it.

2. The whole idea of "gvim" feels like it has been deprecated with NeoVim, what with the `gui_` features and settings mostly being removed. I'd prefer it if the `has(...)` test was the way to detect different clients.

3. People who have `.gvimrc` files will most likely have filled them with gvim-specific commands like `guifont` etc., which have been removed so will just cause errors. People who don't already have `.gvimrc` files can just use `if has('gui_running')` to set gui-specific settings, whether by sourcing another file or not.

**Comment by shazow** [comment]
Agreed.

The whole guifont issue is interesting too, since each frontend seems to have its own way to specify font configuration. That's fairly frustrating but not specifically neovim-dot-app's fault. Perhaps an opportunity to establish somekind of reasonable standard.

Also the notion that frontends are decoupled from neovim itself (unlike compiled into vim), so you could have a multitude of different frontends running. Still, it feels like there should be a way to provide configuration specific to each frontend (the `has(...)` approach sounds sensible).

**Comment by sheharyarn** [comment]
Yes, I came looking for the `if has('gui_running')` replacement for neovim.app. Hoping this gets implemented soon! Thanks! :smile:

**Comment by alexeymuranov** [comment]
:+1:

**Comment by beaumartinez** [comment]
Loading `~/.gvimrc` automatically would be cool.

(For now, I'm simply running `:source ~/.gvimrc` when it loads.)

**Comment by ViViDboarder** [comment]
I'm becoming a little confused about what is and isn't implemented.

If I put in my rc file `echom has('gui_running')` it echos `0`. But, after it's loaded `echo has('gui_running')` echos `1`.

Am I doing something wrong? Does the rc get run before the gui attaches or something?

**Comment by ViViDboarder** [comment]
Seems intentional: https://github.com/neovim/neovim/issues/2216 https://github.com/neovim/python-client/issues/106

Oh well...

**Comment by alexeymuranov** [comment]
@rogual, could you please explain your suggested workaround with `if has('gui_running')`?  It does not work from `init.vim`, as observed by @ViViDboarder.

**Comment by rogual** [comment]
You could (rather uglily) use:
```if exists("*MacMenu")```

**Comment by rogual** [comment]
In fact, let's just fix this now. As of 1983e1339ff53c451d110691bc5907c14718d5ec you can use

```if exists("neovim_dot_app")```

**Comment by sheharyarn** [comment]
:+1:

**Comment by alexeymuranov** [comment]
This still does not work from `init.vim` for me.

**Comment by alexeymuranov** [comment]
Thanks, it works!

**Comment by rogual** [comment]
Neato. Going to close this now.

**Comment by jamischarles** [comment]
@rogual Coming in late, but here's a thought. What about also adding `gui_running` variable? I switched from `macvim` yesterday and I had to go through and rename all my `if` blocks. It's be nice if gui's all use `gui_running` as well to make switching easier.

Granted, this isn't a very frequent use case. Thoughts?

**Comment by rogual** [comment]
I've opened an issue with Neovim to try and get https://github.com/rogual/neovim-dot-app/issues/157 resolved — basically, asking them to let us force Neovim to report gui_running. Let's see what they say. If they don't want to do that, your idea is good too.

**Comment by jamischarles** [comment]
While we're at it, what if we asked them to allow a consistent mapping for the cmd key? You use `<T>`. Would be great if neovim supported and highlighted that.

**Comment by rogual** [comment]
I think if Neovim were to change anything about the mappings it would be to define an actual Command modifier rather than a platform-dependent "Super" modifier. I don't mind either way; ask them if you like!

**Comment by sheharyarn** [comment]
I agree with @jamischarles; I think it should have both `gui_running` and `neovim_dot_app` set.
